/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as HomeRouteImport } from './routes/home'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PUsernameRouteImport } from './routes/p.$username'
import { Route as VagasIndexRouteImport } from './routes/vagas.index'
import { Route as VagasPublicarRouteImport } from './routes/vagas.publicar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PUsernameRoute = PUsernameRouteImport.update({
  id: '/p/$username',
  path: '/p/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const VagasIndexRoute = VagasIndexRouteImport.update({
  id: '/vagas/',
  path: '/vagas/',
  getParentRoute: () => rootRouteImport,
} as any)
const VagasPublicarRoute = VagasPublicarRouteImport.update({
  id: '/vagas/publicar',
  path: '/vagas/publicar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/home': typeof HomeRoute
  '/perfil': typeof PerfilRoute
  '/p/$username': typeof PUsernameRoute
  '/vagas/publicar': typeof VagasPublicarRoute
  '/vagas/': typeof VagasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/home': typeof HomeRoute
  '/perfil': typeof PerfilRoute
  '/p/$username': typeof PUsernameRoute
  '/vagas/publicar': typeof VagasPublicarRoute
  '/vagas': typeof VagasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/home': typeof HomeRoute
  '/perfil': typeof PerfilRoute
  '/p/$username': typeof PUsernameRoute
  '/vagas/publicar': typeof VagasPublicarRoute
  '/vagas/': typeof VagasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/home'
    | '/perfil'
    | '/p/$username'
    | '/vagas/publicar'
    | '/vagas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/home'
    | '/perfil'
    | '/p/$username'
    | '/vagas/publicar'
    | '/vagas'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/home'
    | '/perfil'
    | '/p/$username'
    | '/vagas/publicar'
    | '/vagas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  HomeRoute: typeof HomeRoute
  PerfilRoute: typeof PerfilRoute
  PUsernameRoute: typeof PUsernameRoute
  VagasPublicarRoute: typeof VagasPublicarRoute
  VagasIndexRoute: typeof VagasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$username': {
      id: '/p/$username'
      path: '/p/$username'
      fullPath: '/p/$username'
      preLoaderRoute: typeof PUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vagas/': {
      id: '/vagas/'
      path: '/vagas'
      fullPath: '/vagas/'
      preLoaderRoute: typeof VagasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vagas/publicar': {
      id: '/vagas/publicar'
      path: '/vagas/publicar'
      fullPath: '/vagas/publicar'
      preLoaderRoute: typeof VagasPublicarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  HomeRoute: HomeRoute,
  PerfilRoute: PerfilRoute,
  PUsernameRoute: PUsernameRoute,
  VagasPublicarRoute: VagasPublicarRoute,
  VagasIndexRoute: VagasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
